language: go
go:
- 1.9.x
- 1.10.x
- 1.11.x
- 1.x
os:
- linux
- osx
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- "$HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN"
