build: off

clone_folder: c:\gopath\src\github.com\bvinc\go-sqlite-lite

environment:
  GOPATH: c:\gopath
  GETH_ARCH: amd64
  MSYS2_ARCH: x86_64
  MSYS2_BITS: 64
  MSYSTEM: MINGW64
  PATH: C:\msys64\mingw64\bin\;%PATH%

stack: go 1.10

before_test:
  - go vet ./...

test_script:
  - go test ./...
