build: off

clone_folder: c:\gopath\src\github.com\bvinc\go-sqlite-lite

environment:
  GOPATH: c:\gopath
  matrix:
    - GETH_ARCH: amd64
      MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      PATH: C:\msys64\mingw64\bin\;%PATH%
    - GETH_ARCH: 386
      MSYS2_ARCH: i686
      MSYS2_BITS: 32
      MSYSTEM: MINGW32
      PATH: C:\msys64\mingw32\bin\;%PATH%

stack: go 1.10

before_test:
  - go vet ./...

test_script:
  - go test ./...
